<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container70CXGsa\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container70CXGsa/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container70CXGsa.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container70CXGsa\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container70CXGsa\appAppKernelProdContainer([
    'container.build_hash' => '70CXGsa',
    'container.build_id' => 'a7549935',
    'container.build_time' => 1698150439,
], __DIR__.\DIRECTORY_SEPARATOR.'Container70CXGsa');
