<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5mrzVwD\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5mrzVwD/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container5mrzVwD.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container5mrzVwD\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container5mrzVwD\appAppKernelProdContainer([
    'container.build_hash' => '5mrzVwD',
    'container.build_id' => '453ffc09',
    'container.build_time' => 1698150475,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5mrzVwD');
